variables:
  ROS_DISTRO: jazzy

image: osrf/ros:$ROS_DISTRO-simulation

stages:
  - build
  - test

before_script:
  - git config --global user.name "Gitlab Runner"
  - git config --global user.email "<>"
  - apt-get update

Build:
  stage: build
  script:
    - source /opt/ros/$ROS_DISTRO/setup.bash
    - mkdir -p build/src
    - cd build
    - git clone --local .. src/${CI_PROJECT_NAME}
    - rosdep update --rosdistro $ROS_DISTRO
    - rosdep install --from-path src --rosdistro $ROS_DISTRO -y --skip-keys="gazebo rviz joint_state_publisher_gui" --dependency-types=build 
    - colcon build --packages-up-to ${CI_PROJECT_NAME} --cmake-args -DBUILD_TESTING=ON --event-handlers console_direct+ summary+ status-
  artifacts:
    paths:
      - 'build/install'
    expire_in: 4 hrs

Test:
  stage: test
  script:
    - apt-get install iproute2 -y
    - ip link add dev vcan0 type dummy
    - ip link set up vcan0
    - cd build
    - source ${CI_PROJECT_DIR}/build/install/setup.bash
    - rosdep install --from-path . --rosdistro $ROS_DISTRO -y --skip-keys="gazebo rviz joint_state_publisher_gui" --dependency-types=test --dependency-types=exec
    - colcon test --packages-select ${CI_PROJECT_NAME} 
    - colcon test-result --all --verbose
  needs: 
    - job: Build
      artifacts: true