cubermars_hardware_node:
  ros__parameters:
    joints: ["joint_1", "joint_2", "joint_3","joint_4", "joint_5", "joint_6"]
    default_damping_KD: 1.0
    watchdog_frequency: 10
    friction_compensation_sign_steepness: 100.


    joint_defintions:
      joint_1:
        msg_idx: 0
        can_interface: "can0"
        can_id: 1
        motor_type: "AK10-9"
        cf: 0.22
      
      joint_2:
        msg_idx: 1
        can_interface: "can0"
        can_id: 2
        motor_type: "AK10-9"
        cf: 0.22

      joint_3:
        msg_idx: 2
        can_interface: "can0"
        can_id: 3
        motor_type: "AK10-9"
        cf: 0.22

      joint_4:
        msg_idx: 3
        can_interface: "can1"
        can_id: 4
        motor_type: "AK10-9"
        cf: 0.22
      
      joint_5:
        msg_idx: 4
        can_interface: "can1"
        can_id: 5
        motor_type: "AK10-9"
        cf: 0.22

      joint_6:
        msg_idx: 5
        can_interface: "can1"
        can_id: 6
        motor_type: "AK10-9"
        cf: 0.22


